spring:
  application:
    name: KAAD-back-end
  datasource:
    url: jdbc:postgresql://localhost:5432/kaad
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration



application:
  security:
    jwt:
      secret-key: <secretKey>
      refresh-secret-key: <secretKey>
      expiration-time: 300000
      refresh-expiration-time: 120000000
    cors:
      allowed-origin: https://service-center-rro.com.ua