spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

  application:
    name: KAAD-back-end
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: validate #change to validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}



application:
  contact:
    creationTimeout: 2
    mail: ${MAIL_SEND_TO}

  security:
    jwt:
      secret-key: ${JWT_TOKEN}
      refresh-secret-key: ${JWT_REFRESH_TOKEN}
      expiration-time: 300000
      refresh-expiration-time: 120000000_000_000_000
    cors:
      allowed-origin: ${ALLOWED_ORIGIN}