create table contact (
     id bigint generated by default as identity,
     uuid varchar(255) not null,
     created_at timestamp(6) with time zone not null,
     email varchar(255),
     full_name varchar(255) not null,
     phone_number varchar(255),
     reason varchar(255) not null,
     resolved boolean not null,
     contact_type_id bigint,
     primary key (id),
    constraint fk_contact_type foreign key (contact_type_id) references contact_type
)