create table general_info (
    id bigint generated by default as identity,
    code varchar(255) not null,
    content TEXT not null,
    language_id bigint,
    is_label boolean,
    primary key (id),
        constraint fk_language foreign key (language_id) references language
);