
create table specialization_page (
         id bigint generated by default as identity,
         content TEXT not null,
         primary key (id)
);


create table specialization (
        id bigint generated by default as identity,
        image_data oid not null,
        img_name varchar(255) not null,
        spec_page bigint,
        primary key (id),
        constraint fk_spec_page foreign key (spec_page) references specialization_page
);

create table specialization_details (
    specialization_id bigint not null,
    details_id bigint not null,
    constraint fk_general_info foreign key (details_id) references  general_info,
    constraint fk_spec foreign key (specialization_id) references specialization
)

