
create table specialization (
    id bigint generated by default as identity,
    image_data oid,
    img_name varchar(255),
    is_hidden boolean not null,
    primary key (id)
);

create table specialization_page (
     id bigint not null,
     image_data oid,
     image_name varchar(255),
     primary key (id),
     constraint fk_spec_id foreign key (id) references specialization
);

create table specialization_spec_names (
    specialization_id bigint not null,
    spec_names_id bigint not null,
    constraint fk_general_info foreign key (spec_names_id) references  general_info,
    constraint fk_spec foreign key (specialization_id) references specialization
);

create table specialization_page_content (
    specialization_page_id bigint not null,
    content_id bigint not null,
    constraint fk_general_info foreign key (content_id) references  general_info,
    constraint fk_spec_page foreign key (specialization_page_id) references specialization_page
)
