create table contact_type (
      id bigint generated by default as identity,
      contact_type varchar(255) not null,
      primary key (id)
);

insert into contact_type (contact_type) values ('Telegram');
insert into contact_type (contact_type) values ('WhatsApp');
insert into contact_type (contact_type) values ('Messenger');
insert into contact_type (contact_type) values ('Email');
insert into contact_type (contact_type) values ('Viber');
insert into contact_type (contact_type) values ('SMS');
insert into contact_type (contact_type) values ('Telefoniczne');